import{collection,getDocs,query,where,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,increment}from'firebase/firestore';import{db,firebaseReady}from'../firebase';import{seedPosts,listings as seedListings}from'../data/seed';
export async function getPosts(){if(!firebaseReady)return seedPosts;const s=await getDocs(query(collection(db,'posts'),where('isPublished','==',true)));return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function getListings(){if(!firebaseReady)return seedListings;const s=await getDocs(query(collection(db,'listings'),where('isPublished','==',true)));return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function getAll(name){if(!firebaseReady)return name==='posts'?seedPosts:seedListings;const s=await getDocs(collection(db,name));return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function createItem(name,data){if(!firebaseReady)throw new Error('Add Firebase values to .env first.');return addDoc(collection(db,name),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function updateItem(name,id,data){return updateDoc(doc(db,name,id),{...data,updatedAt:serverTimestamp()});}export async function removeItem(name,id){return deleteDoc(doc(db,name,id));}
export async function bumpView(id){if(firebaseReady)try{await updateDoc(doc(db,'posts',id),{views:increment(1)})}catch{}}

export async function getSiteSettings(){if(!firebaseReady)return{aboutTitle:"About Moji's Heritage",aboutBody:"Moji's Heritage is a digital home for learning about Nigeria's histories, peoples, languages, festivals, foods, landmarks and living traditions.",vision:"To make Nigeria's diverse cultural heritage accessible, engaging and discoverable for present and future generations.",mission:"To document, teach and share trustworthy cultural knowledge while connecting readers with the places and communities that keep heritage alive."};const{getDoc}=await import('firebase/firestore');const s=await getDoc(doc(db,'siteSettings','general'));return s.exists()?s.data():{};}
export async function saveSiteSettings(data){if(!firebaseReady)throw new Error('Firebase is not configured.');const{setDoc}=await import('firebase/firestore');return setDoc(doc(db,'siteSettings','general'),{...data,updatedAt:serverTimestamp()},{merge:true});}
